import { envValue } from "../../src/server/runtime.mjs";
import { authorizeRequest } from "../../src/server/auth.mjs";
import { companyKey } from "../../src/server/company-memory.mjs";
import { getStateRepository } from "../../src/server/netlify-state.mjs";
import { sourceVerificationSatisfied } from "../../src/lib/domain.mjs";
import { isSalesOpportunityRecord } from "../../src/server/record-classification.mjs";
const json=(payload,status=200)=>Response.json(payload,{status,headers:{"cache-control":"no-store"}});
export default async function handler(request, context){if(request.method!=="POST")return json({ok:false,error:{code:"METHOD_NOT_ALLOWED",message:"Use POST /api/company-state."}},405);const auth=authorizeRequest(request,envValue("RADAR_INTERNAL_ACCESS_SECRET"));if(!auth.ok)return json({ok:false,error:{code:auth.code,message:auth.status===503?"Internal access is not configured on the server.":"Invalid internal access code."}},auth.status);const body=await request.json().catch(()=>({}));if(!body.company||typeof body.action!=="string")return json({ok:false,error:{code:"INVALID_COMPANY_ACTION",message:"company and action are required."}},400);const repo=await getStateRepository(request, context);const nowIso=new Date().toISOString();try{if(body.action==="SET_BOOKMARK"){if(typeof body.bookmarked!=="boolean")return json({ok:false,error:{code:"INVALID_BOOKMARK",message:"bookmarked must be boolean."}},400);const company=await repo.setBookmark(body.company,body.bookmarked,nowIso);return json({ok:true,company});}if(body.action==="MARK_EMAIL_SENT"){if(!body.opportunity_id)return json({ok:false,error:{code:"OPPORTUNITY_REQUIRED",message:"opportunity_id is required when marking email sent."}},400);const opportunity=await repo.getOpportunity(body.opportunity_id);if(!opportunity)return json({ok:false,error:{code:"OPPORTUNITY_NOT_FOUND",message:"Opportunity was not found in shared history."}},404);if(companyKey(opportunity.company)!==companyKey(body.company))return json({ok:false,error:{code:"COMPANY_MISMATCH",message:"Opportunity does not belong to this company."}},409);if(!isSalesOpportunityRecord(opportunity))return json({ok:false,error:{code:"RECORD_NOT_SALES_OPPORTUNITY",message:"Outreach is locked for competitor and source-platform records."}},409);if(!sourceVerificationSatisfied(opportunity))return json({ok:false,error:{code:"SOURCE_MANUAL_VERIFICATION_REQUIRED",message:"Open and manually verify the original source before recording outreach."}},409);const company=await repo.markEmailSent(opportunity.company,{opportunityId:opportunity.id,recipient:opportunity.contact_email||null,subject:opportunity.reply_subject||null,sourceUrl:opportunity.source_url||null,sentAt:nowIso});const updatedOpportunity=await repo.getOpportunity(opportunity.id);return json({ok:true,company,opportunity:updatedOpportunity});}return json({ok:false,error:{code:"UNKNOWN_COMPANY_ACTION",message:"Unknown company action."}},400);}catch(error){console.error("[radar-state] COMPANY_WRITE_FAILED");return json({ok:false,error:{code:error?.code||"COMPANY_WRITE_FAILED",message:String(error?.message||"Could not save company state.").slice(0,300)}},Number(error?.status)||500);}}
export const config={path:"/api/company-state"};
