import test from "node:test";import assert from "node:assert/strict";import { createStateRepository } from "../src/server/state-repository.mjs";
function memoryStore(){const d=new Map();return{async setJSON(k,v){d.set(k,structuredClone(v));},async get(k){return d.has(k)?structuredClone(d.get(k)):null;},async list({prefix}={}){return{blobs:[...d.keys()].filter(k=>!prefix||k.startsWith(prefix)).map(key=>({key,etag:"x"})),directories:[]};}};}
const request=()=>new Request("https://radar.test/api/generate-response",{method:"POST",headers:{authorization:"Bearer secret","content-type":"application/json"},body:JSON.stringify({opportunity_id:"opp"})});
test("generate response server owns TO and persists reply",async()=>{const repo=createStateRepository(memoryStore());await repo.saveOpportunity({id:"opp",company:"Buyer",contact_email:"public@buyer.example",status:"NEW"});globalThis.__RADAR_TEST_STATE_REPOSITORY__=repo;globalThis.__RADAR_TEST_REPLY_RUNNER__=async()=>({subject:"Subject",body:"Body text that passed mocked validation",model:"mock",response_id:"r1",attempts:1,usage:null});globalThis.Netlify={env:{get:(key)=>({RADAR_INTERNAL_ACCESS_SECRET:"secret",RADAR_LIVE_AI_ENABLED:"true",RADAR_PRODUCTION_REPLY_ENABLED:"true",OPENAI_API_KEY:"fake"}[key]||"")}};const{default:handler}=await import(`../netlify/functions/generate-response.mjs?x=${Date.now()}`);const res=await handler(request(),{deploy:{context:"production"}});const payload=await res.json();assert.equal(res.status,200);assert.equal(payload.reply.to,"public@buyer.example");assert.equal((await repo.getOpportunity("opp")).reply_subject,"Subject");});

test("response generation rejects unverified discovery before calling the model",async()=>{const repo=createStateRepository(memoryStore()),source="https://www.upwork.com/freelance-jobs/apply/Human-Scan-Cleanup_~0123";await repo.saveOpportunity({id:"opp",company:"Buyer",status:"NEW",source_url:source,discovery_mode:"INDEX_DISCOVERY_MANUAL_VERIFY",manual_verification_status:"REQUIRED_BEFORE_CONTACT",manual_verified_at:null,manual_verified_source_url:null});globalThis.__RADAR_TEST_STATE_REPOSITORY__=repo;let calls=0;globalThis.__RADAR_TEST_REPLY_RUNNER__=async()=>{calls+=1;throw new Error("must not run");};globalThis.Netlify={env:{get:(key)=>({RADAR_INTERNAL_ACCESS_SECRET:"secret",RADAR_LIVE_AI_ENABLED:"true",RADAR_PRODUCTION_REPLY_ENABLED:"true",OPENAI_API_KEY:"fake"}[key]||"")}};const{default:handler}=await import(`../netlify/functions/generate-response.mjs?verify=${Date.now()}`);const res=await handler(request(),{deploy:{context:"production"}});assert.equal(res.status,409);assert.equal((await res.json()).error.code,"SOURCE_MANUAL_VERIFICATION_REQUIRED");assert.equal(calls,0);});

test("response generation rejects competitor records before calling the model",async()=>{const repo=createStateRepository(memoryStore());await repo.saveOpportunity({id:"opp",record_kind:"COMPETITOR",company:"Seller",status:"NEW",source_url:"https://seller.example/services",contact_email:"historic@seller.example"});globalThis.__RADAR_TEST_STATE_REPOSITORY__=repo;let calls=0;globalThis.__RADAR_TEST_REPLY_RUNNER__=async()=>{calls+=1;throw new Error("must not run");};globalThis.Netlify={env:{get:(key)=>({RADAR_INTERNAL_ACCESS_SECRET:"secret",RADAR_LIVE_AI_ENABLED:"true",RADAR_PRODUCTION_REPLY_ENABLED:"true",OPENAI_API_KEY:"fake"}[key]||"")}};const{default:handler}=await import(`../netlify/functions/generate-response.mjs?competitor=${Date.now()}`);const res=await handler(request(),{deploy:{context:"production"}});assert.equal(res.status,409);assert.equal((await res.json()).error.code,"RECORD_NOT_SALES_OPPORTUNITY");assert.equal(calls,0);});

test("global live AI cannot unlock production reply without its dedicated gate",async()=>{let calls=0;globalThis.__RADAR_TEST_REPLY_RUNNER__=async()=>{calls+=1;throw new Error("must not run");};globalThis.Netlify={env:{get:(key)=>({RADAR_INTERNAL_ACCESS_SECRET:"secret",RADAR_LIVE_AI_ENABLED:"true",RADAR_PRODUCTION_REPLY_ENABLED:"false",OPENAI_API_KEY:"fake"}[key]||"")}};const{default:handler}=await import(`../netlify/functions/generate-response.mjs?gate=${Date.now()}`);const res=await handler(request(),{deploy:{context:"production"}});assert.equal(res.status,423);assert.equal((await res.json()).error.code,"PRODUCTION_REPLY_LOCKED");assert.equal(calls,0);});
