import test from "node:test";
import assert from "node:assert/strict";
import { approvedProfile, buildReplyRequest } from "../src/server/reply-contract.mjs";
import { parseReplyResponse, runReplyGeneration } from "../src/server/openai-reply.mjs";
const profile={company:"3D.sk",capabilities:[{id:"safe",status:"APPROVED",outbound_safe:true,label:"Safe capability"},{id:"unsafe",status:"DRAFT",outbound_safe:false,label:"Unsafe"}],credentials:[{id:"credit",status:"PUBLIC_APPROVED",outbound_safe:true,verification_url:"https://example.com",label:"Public credit"},{id:"secret",status:"PRIVATE",outbound_safe:false,label:"Private client"}],restricted_claims:[{id:"r",rule:"No promises"}],reply_rules:{}};
const opportunity={title:"Realistic human vendor",company:"Buyer",summary:"Needs scan cleanup and Wrap",opportunity_kind:"OPEN_OPPORTUNITY",categories:["WRAP_BASEMESH"],location:"Worldwide",remote_scope:"WORLDWIDE_VENDOR",published_date:"2026-09-05",why_it_fits:["match"],risks:[],missing_requirements:[],contact_name:null,contact_role:null,source_url:"https://example.com/job",source_evidence:[]};
test("reply prompt receives only approved outbound-safe authority",()=>{const safe=approvedProfile(profile);assert.deepEqual(safe.capabilities.map(x=>x.id),["safe"]);assert.deepEqual(safe.credentials.map(x=>x.id),["credit"]);const body=JSON.stringify(buildReplyRequest({profile,opportunity}));assert.doesNotMatch(body,/Private client/);assert.doesNotMatch(body,/Unsafe/);});
test("reply parser rejects unapproved ids",()=>{const raw={output_text:JSON.stringify({subject:"Hello",body:Array(90).fill("word").join(" "),used_capability_ids:["unsafe"],used_credential_ids:[]})};assert.throws(()=>parseReplyResponse(raw,profile),/unapproved capability/);});
test("reply generation permits only one structured retry",async()=>{let calls=0;const fetchImpl=async()=>{calls++;return new Response(JSON.stringify({id:`r${calls}`,model:"gpt-5.6-sol",output_text:calls===1?"{}":JSON.stringify({subject:"Relevant production support",body:Array(120).fill("word").join(" "),used_capability_ids:["safe"],used_credential_ids:[]})}),{status:200,headers:{"content-type":"application/json"}});};const result=await runReplyGeneration({apiKey:"test",model:"gpt-5.6-sol",profile,opportunity,fetchImpl});assert.equal(result.attempts,2);assert.equal(calls,2);});
