import { bandForScore, contactDisplay, STATUS_VALUES } from "./lib/domain.mjs";

const STATUS_STORAGE_KEY = "3dsk-radar-fixture-status-v2";
const ACCESS_SESSION_KEY = "3dsk-radar-access-v2";
const state = { opportunities:[], companies:new Map(), selectedId:null, view:"ALL", status:"ALL", minFit:0, datasetMode:"FIXTURE", lastRun:null };
const els = {
  body:document.querySelector("#opportunity-body"), detail:document.querySelector("#detail-panel"), summary:document.querySelector("#summary-grid"), count:document.querySelector("#result-count"),
  find:document.querySelector("#find-button"), connect:document.querySelector("#connect-button"), scanNote:document.querySelector("#scan-note"), statusFilter:document.querySelector("#status-filter"), fitFilter:document.querySelector("#fit-filter"),
  toast:document.querySelector("#toast"), accessCode:document.querySelector("#access-code"), datasetPill:document.querySelector("#dataset-pill")
};
const escapeHtml = (value) => String(value ?? "").replace(/[&<>'\"]/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
const companyMapKey = (company) => String(company || "").trim().toLowerCase();

function readFixtureStatuses(){ try{return JSON.parse(localStorage.getItem(STATUS_STORAGE_KEY)||"{}");}catch{return {};} }
function hydrateFixtureStatuses(items){ const saved=readFixtureStatuses(); return items.map((item)=>({...item,status:STATUS_VALUES.includes(saved[item.id])?saved[item.id]:item.status,company_bookmarked:false,company_last_contacted_at:null,company_contact_count:0})); }
function saveFixtureStatus(id,status){ localStorage.setItem(STATUS_STORAGE_KEY,JSON.stringify({...readFixtureStatuses(),[id]:status})); }
function companyStateFor(item){ return state.companies.get(item.company_key || companyMapKey(item.company)) || { company:item.company, bookmarked:Boolean(item.company_bookmarked), last_contacted_at:item.company_last_contacted_at||null, contact_count:item.company_contact_count||0, contact_history:[] }; }
function applyCompanyState(company){ state.companies.set(company.company_key || companyMapKey(company.company),company); for(const item of state.opportunities){ if((item.company_key&&company.company_key&&item.company_key===company.company_key)||companyMapKey(item.company)===companyMapKey(company.company)){ item.company_key=company.company_key||item.company_key; item.company_bookmarked=Boolean(company.bookmarked); item.company_last_contacted_at=company.last_contacted_at||null; item.company_contact_count=company.contact_count||0; } } }
function accessCode(){ return els.accessCode.value.trim(); }
function authHeaders(){ return {"content-type":"application/json","authorization":`Bearer ${accessCode()}`}; }
async function api(path,options={}){ const response=await fetch(path,{...options,headers:{...authHeaders(),...(options.headers||{})}}); const payload=await response.json().catch(()=>({})); if(!response.ok||!payload.ok) throw new Error(payload?.error?.message||`${path} failed (${response.status})`); return payload; }

function filtered(){ return state.opportunities.filter((item)=>{
  const viewOk=state.view==="ALL"||(state.view==="BOOKMARKED"&&item.company_bookmarked)||(state.view===item.opportunity_kind);
  return viewOk&&(state.status==="ALL"||item.status===state.status)&&item.fit_score>=state.minFit;
}).sort((a,b)=>b.win_score-a.win_score||b.fit_score-a.fit_score); }
function formatDate(value){ if(!value)return"Date unknown"; const date=new Date(`${value}T00:00:00Z`); return Number.isNaN(date.getTime())?"Date unknown":new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric"}).format(date); }
function formatTimestamp(value){ if(!value)return"Never"; const date=new Date(value); return Number.isNaN(date.getTime())?"Unknown":new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(date); }
function daysSince(value){ if(!value)return null; const ts=new Date(value).getTime(); return Number.isFinite(ts)?Math.max(0,Math.floor((Date.now()-ts)/86400000)):null; }
function freshness(value){ const days=value?daysSince(`${value}T00:00:00Z`):null; if(days===null)return"date unknown"; if(days===0)return"today"; if(days===1)return"1 day ago"; return`${days} days ago`; }
function budgetView(item){ if(item.budget_type==="PUBLISHED")return{value:item.budget_published,meta:"PUBLISHED",cls:"published"}; if(item.budget_type==="ESTIMATED")return{value:`${item.budget_currency||""} ${Number(item.budget_estimated_min).toLocaleString("en-US")}–${Number(item.budget_estimated_max).toLocaleString("en-US")}`,meta:`ESTIMATED · ${item.budget_confidence||"unknown"} confidence`,cls:"estimated"}; return{value:"Budget unknown",meta:"UNKNOWN",cls:"unknown"}; }
function kindBadge(item){ const open=item.opportunity_kind==="OPEN_OPPORTUNITY"; return`<span class="kind-badge ${open?"open":"lead"}">${open?"OPEN OPPORTUNITY":"POTENTIAL LEAD"}</span>`; }
function scoreMarkup(label,score){ const band=bandForScore(score); return`<span class="score ${band.toLowerCase()}"><strong>${score}</strong><small>${escapeHtml(label)} · ${band}</small></span>`; }
function statusOptions(selected){ return STATUS_VALUES.map((s)=>`<option value="${s}" ${s===selected?"selected":""}>${s}</option>`).join(""); }
function outreachMarkup(item){ const company=companyStateFor(item); if(!company.last_contacted_at)return'<span class="outreach none">NOT EMAILED</span>'; const days=daysSince(company.last_contacted_at); const recent=days!==null&&days<=30; return`<span class="outreach ${recent?"recent":"past"}">EMAILED ${days===0?"TODAY":`${days}D AGO`}</span><span class="company">${company.contact_count||1}× total</span>`; }

function renderSummary(){ const all=state.opportunities; const uniqueCompanies=new Set(all.map((x)=>companyMapKey(x.company))).size; const bookmarked=new Set(all.filter((x)=>x.company_bookmarked).map((x)=>companyMapKey(x.company))).size; const contacted=new Set(all.filter((x)=>x.company_last_contacted_at).map((x)=>companyMapKey(x.company))).size; const cards=[["OPPORTUNITIES",all.length,state.datasetMode.toLowerCase()],["COMPANIES",uniqueCompanies,"unique buyers"],["BOOKMARKED",bookmarked,"companies"],["EMAILED",contacted,"companies with history"],["HIGH FIT",all.filter((x)=>x.fit_score>=80).length,"FIT 80+"]]; els.summary.innerHTML=cards.map(([l,v,s])=>`<article class="summary-card"><span class="label">${escapeHtml(l)}</span><strong class="value">${escapeHtml(v)}</strong><span class="sub">${escapeHtml(s)}</span></article>`).join(""); }
function renderTable(){ const items=filtered(); els.count.textContent=`${items.length} shown · ${state.opportunities.length} total`; if(!items.length){els.body.innerHTML='<tr><td colspan="13">No opportunities match these filters.</td></tr>';return;} els.body.innerHTML=items.map((item)=>{const budget=budgetView(item);return`<tr data-id="${escapeHtml(item.id)}" class="${item.id===state.selectedId?"is-selected":""}">
<td><input class="select-radio" type="radio" name="selected-opportunity" ${item.id===state.selectedId?"checked":""}></td>
<td><button class="star-button ${item.company_bookmarked?"is-starred":""}" data-bookmark-company="${escapeHtml(item.company)}" type="button" title="${item.company_bookmarked?"Remove company bookmark":"Bookmark company"}">${item.company_bookmarked?"★":"☆"}</button></td>
<td>${scoreMarkup("FIT",item.fit_score)}</td><td>${scoreMarkup("WIN",item.win_score)}</td>
<td><span class="opportunity-title">${escapeHtml(item.title)}</span></td>
<td><span class="company-name">${escapeHtml(item.company)}</span>${item.company_bookmarked?'<span class="bookmarked-label">BOOKMARKED</span>':""}</td>
<td>${kindBadge(item)}<div class="minor-line">${escapeHtml(item.categories[0])}</div></td>
<td class="budget-cell"><span class="budget-value">${escapeHtml(budget.value)}</span><span class="provenance ${budget.cls}">${escapeHtml(budget.meta)}</span></td>
<td>${escapeHtml(formatDate(item.published_date))}<span class="company">${escapeHtml(freshness(item.published_date))}</span></td>
<td>${outreachMarkup(item)}</td>
<td class="${item.contact_email?"contact-yes":"contact-no"}">${escapeHtml(contactDisplay(item))}</td>
<td><select class="status-select" data-status-id="${escapeHtml(item.id)}">${statusOptions(item.status)}</select></td>
<td><a class="source-link" href="${escapeHtml(item.source_url)}" target="_blank" rel="noreferrer">OPEN</a></td></tr>`;}).join(""); }
function bullets(items,empty){ return items?.length?`<ul>${items.map((x)=>`<li>${escapeHtml(x)}</li>`).join("")}</ul>`:`<p>${escapeHtml(empty)}</p>`; }
function evidenceMarkup(item){ return item.source_evidence?.length?`<ul class="evidence-list">${item.source_evidence.map((e)=>`<li><a href="${escapeHtml(e.url)}" target="_blank" rel="noreferrer">${escapeHtml(e.type)}</a><span>${escapeHtml(e.note)}</span></li>`).join("")}</ul>`:"<p>No source evidence recorded.</p>"; }
function historyMarkup(company){ if(!company.contact_history?.length)return"<p>Never contacted.</p>"; return`<ul class="history-list">${company.contact_history.slice(0,5).map((x)=>`<li><strong>${escapeHtml(formatTimestamp(x.sent_at))}</strong><span>${escapeHtml(x.recipient||"Recipient not recorded")}${x.subject?` · ${escapeHtml(x.subject)}`:""}</span></li>`).join("")}</ul>`; }
function replyMarkup(item){if(!item.reply_subject||!item.reply_body)return"";const to=item.reply_to||item.contact_email||"Email not publicly available";return`<div class="detail-section reply-section"><h4>GENERATED RESPONSE</h4><div class="reply-field"><span>TO</span><strong>${escapeHtml(to)}</strong></div><div class="reply-field"><span>SUBJECT</span><strong>${escapeHtml(item.reply_subject)}</strong></div><div class="reply-body">${escapeHtml(item.reply_body).replace(/\n/g,"<br>")}</div><p class="muted reply-meta">Generated ${escapeHtml(formatTimestamp(item.reply_generated_at))}${item.reply_model?` · ${escapeHtml(item.reply_model)}`:""}</p></div>`;}
function renderDetail(){ const item=state.opportunities.find((x)=>x.id===state.selectedId); if(!item){els.detail.innerHTML='<div class="detail-empty">Select an opportunity.</div>';return;} const budget=budgetView(item),company=companyStateFor(item),days=daysSince(company.last_contacted_at),recent=days!==null&&days<=30; const contact=item.contact_email?`<p><strong>${escapeHtml(item.contact_email)}</strong><br><span class="muted">Public source verified.</span></p>`:'<p><strong>Email not publicly available</strong><br><span class="muted">No address will be inferred.</span></p>'; els.detail.innerHTML=`
<div class="detail-head"><div class="detail-title-row"><div><p class="eyebrow">${item.opportunity_kind==="OPEN_OPPORTUNITY"?"OPEN OPPORTUNITY":"POTENTIAL LEAD · NOT AN ACTIVE REQUEST"}</p><h3>${escapeHtml(item.title)}</h3><p class="detail-company">${escapeHtml(item.company)} · ${escapeHtml(item.location)}</p></div><button class="star-button detail-star ${item.company_bookmarked?"is-starred":""}" data-bookmark-company="${escapeHtml(item.company)}" type="button">${item.company_bookmarked?"★":"☆"}</button></div><div class="detail-tags">${kindBadge(item)}${item.categories.slice(0,5).map((x)=>`<span class="tag">${escapeHtml(x)}</span>`).join("")}</div></div>
<div class="detail-body">${recent?`<div class="repeat-warning"><strong>RECENT OUTREACH</strong><span>This company was emailed ${days===0?"today":`${days} days ago`}. Review history before sending again.</span></div>`:""}
<div class="score-pair"><div class="score-card"><span>FIT SCORE</span><strong>${item.fit_score}</strong><span>${bandForScore(item.fit_score)} MATCH</span></div><div class="score-card"><span>WIN SCORE</span><strong>${item.win_score}</strong><span>${item.win_band} · HEURISTIC</span></div></div>
<div class="detail-section"><h4>SUMMARY</h4><p>${escapeHtml(item.summary)}</p></div><div class="detail-section"><h4>WHY IT FITS</h4>${bullets(item.why_it_fits,"No fit rationale available.")}</div><div class="detail-section"><h4>RISKS / GAPS</h4>${bullets([...(item.risks||[]),...(item.missing_requirements||[])],"No recorded gaps.")}</div>
<div class="detail-section"><h4>BUDGET</h4><p><strong>${escapeHtml(budget.value)}</strong> · ${escapeHtml(budget.meta)}<br><span class="muted">${escapeHtml(item.budget_reason)}</span></p></div><div class="detail-section"><h4>CONTACT</h4>${contact}</div>
<div class="detail-section"><h4>COMPANY OUTREACH HISTORY</h4><p><strong>${company.contact_count||0} email${company.contact_count===1?"":"s"} recorded</strong>${company.last_contacted_at?` · last ${escapeHtml(formatTimestamp(company.last_contacted_at))}`:""}</p>${historyMarkup(company)}</div>
<div class="detail-section"><h4>SOURCE EVIDENCE</h4>${evidenceMarkup(item)}</div>
${replyMarkup(item)}<div class="detail-actions">${item.contact_email?'<button class="action-button" data-copy="email" type="button">COPY EMAIL</button>':`<a class="action-button" href="${escapeHtml(item.apply_url)}" target="_blank" rel="noreferrer">OPEN CONTACT / APPLY</a>`}<a class="action-button" href="${escapeHtml(item.source_url)}" target="_blank" rel="noreferrer">OPEN SOURCE</a><button class="action-button sent full" data-mark-sent="1" type="button">✓ MARK EMAIL SENT</button><button class="action-button primary full" data-generate-response="1" type="button">${item.reply_body?"REGENERATE RESPONSE":"GENERATE RESPONSE"}</button><button class="action-button" data-copy-subject="1" type="button" ${item.reply_subject?"":"disabled"}>COPY SUBJECT</button><button class="action-button" data-copy-response="1" type="button" ${item.reply_body?"":"disabled"}>COPY RESPONSE</button></div></div>`; }
function renderAll(){renderSummary();renderTable();renderDetail();}
function selectOpportunity(id){state.selectedId=id;renderTable();renderDetail();}
let toastTimer; function showToast(text){clearTimeout(toastTimer);els.toast.textContent=text;els.toast.classList.add("is-visible");toastTimer=setTimeout(()=>els.toast.classList.remove("is-visible"),2400);}
async function copyText(value,label){try{await navigator.clipboard.writeText(value);showToast(`${label} copied`);}catch{showToast("Clipboard unavailable");}}

async function setStatus(id,status){ const item=state.opportunities.find((x)=>x.id===id); if(!item||!STATUS_VALUES.includes(status))return; const old=item.status; item.status=status; renderAll(); try{ if(state.datasetMode==="FIXTURE"){saveFixtureStatus(id,status);showToast(`Fixture status: ${status}`);return;} if(!accessCode())throw new Error("Enter team access code first."); await api("/api/opportunity-status",{method:"POST",body:JSON.stringify({opportunity_id:id,status})}); showToast(`Shared status saved: ${status}`);}catch(error){item.status=old;renderAll();showToast(error.message);} }
async function toggleBookmark(companyName){ const items=state.opportunities.filter((x)=>companyMapKey(x.company)===companyMapKey(companyName)); const next=!items.some((x)=>x.company_bookmarked); if(state.datasetMode==="FIXTURE"){ const company={...companyStateFor(items[0]),company:companyName,bookmarked:next,bookmarked_at:next?new Date().toISOString():null}; applyCompanyState(company); renderAll(); showToast(next?"Fixture company bookmarked":"Fixture bookmark removed"); return;} if(!accessCode()){showToast("Enter team access code first.");return;} try{const payload=await api("/api/company-state",{method:"POST",body:JSON.stringify({action:"SET_BOOKMARK",company:companyName,bookmarked:next})});applyCompanyState(payload.company);renderAll();showToast(next?"Company bookmarked for team":"Company bookmark removed");}catch(error){showToast(error.message);} }
async function markEmailSent(){ const item=state.opportunities.find((x)=>x.id===state.selectedId); if(!item)return; if(state.datasetMode==="FIXTURE"){const now=new Date().toISOString(),current=companyStateFor(item);const company={...current,company:item.company,last_contacted_at:now,contact_count:(current.contact_count||0)+1,contact_history:[{sent_at:now,recipient:item.contact_email||null,subject:null,opportunity_id:item.id},...(current.contact_history||[])]};applyCompanyState(company);item.status="CONTACTED";saveFixtureStatus(item.id,"CONTACTED");renderAll();showToast("Fixture outreach recorded — preview only");return;} if(!accessCode()){showToast("Enter team access code first.");return;} try{const payload=await api("/api/company-state",{method:"POST",body:JSON.stringify({action:"MARK_EMAIL_SENT",company:item.company,opportunity_id:item.id})});applyCompanyState(payload.company);Object.assign(item,payload.opportunity||{});renderAll();showToast("Email marked as sent · company history updated");}catch(error){showToast(error.message);} }
function buildFixtureReply(item){const subject=`${item.company} — realistic character production support`;const capability=item.categories.includes("WRAP_BASEMESH")?"scan cleanup, Wrap to a client-provided basemesh and downstream character preparation":"realistic human character production and scan-based asset finishing";const body=`Hello,\n\nI’m reaching out from 3D.sk regarding your ${item.title}. The scope looks closely aligned with our human-character production pipeline, particularly ${capability}. We can support either a defined part of the pipeline or a broader batch workflow, adapting the handoff to the topology and production requirements you already use.\n\nWhat stood out in your brief is the need for consistent production-ready human assets rather than isolated modeling work. That is the kind of repeatable scan/character workflow our team is set up around.\n\nIf useful, we can review a small sample of your source data and confirm the most efficient handoff point before you define the full batch or request a quotation.\n\nBest regards,\n3D.sk`;return{to:item.contact_email||null,subject,body,generated_at:new Date().toISOString(),model:"FIXTURE_PREVIEW"};}
async function generateResponse(){const item=state.opportunities.find((x)=>x.id===state.selectedId);if(!item)return;if(state.datasetMode==="FIXTURE"){const reply=buildFixtureReply(item);Object.assign(item,{reply_to:reply.to,reply_subject:reply.subject,reply_body:reply.body,reply_generated_at:reply.generated_at,reply_model:reply.model});renderDetail();showToast("Fixture response generated · $0 API cost");return;}if(!accessCode()){showToast("Enter team access code first.");return;}const button=els.detail.querySelector("[data-generate-response]");if(button){button.disabled=true;button.textContent="GENERATING…";}try{const payload=await api("/api/generate-response",{method:"POST",body:JSON.stringify({opportunity_id:item.id})});Object.assign(item,payload.opportunity||{});renderDetail();showToast("Personalized response generated");}catch(error){renderDetail();showToast(error.message);}}
async function loadTeamState(){ if(!accessCode()){showToast("Enter team access code first.");els.accessCode.focus();return;} sessionStorage.setItem(ACCESS_SESSION_KEY,accessCode()); els.connect.disabled=true; try{const payload=await api("/api/opportunities"); if(payload.opportunities.length){state.opportunities=payload.opportunities;state.selectedId=state.opportunities[0]?.id||null;state.companies=new Map();for(const c of payload.companies||[])applyCompanyState(c);state.datasetMode="TEAM";els.datasetPill.textContent=`Shared team state · ${state.opportunities.length}`;els.scanNote.textContent="Shared bookmarks, statuses and outreach history loaded.";renderAll();}else{els.scanNote.textContent="Shared team state is empty · fixtures retained until first live search.";showToast("No stored live opportunities yet");}}catch(error){showToast(error.message);}finally{els.connect.disabled=false;} }
async function runLiveSearch(){ if(!accessCode()){showToast("Enter team access code first.");return;} sessionStorage.setItem(ACCESS_SESSION_KEY,accessCode()); const old=els.find.textContent;els.find.disabled=true;els.find.textContent="SEARCHING…";try{const payload=await api("/api/search",{method:"POST",body:"{}"});state.opportunities=payload.opportunities;state.datasetMode="TEAM";state.lastRun=payload.run;await loadTeamState();els.scanNote.textContent=`Live search complete · ${payload.run.returned_count} records`;showToast("Live search complete");}catch(error){els.scanNote.textContent=`Search not run · ${error.message}`;showToast(error.message);}finally{els.find.disabled=false;els.find.textContent=old;} }

els.body.addEventListener("click",(event)=>{const star=event.target.closest("[data-bookmark-company]");if(star){event.stopPropagation();toggleBookmark(star.dataset.bookmarkCompany);return;}if(event.target.closest("select,a,button,input"))return;const row=event.target.closest("tr[data-id]");if(row)selectOpportunity(row.dataset.id);});
els.body.addEventListener("change",(event)=>{if(event.target.matches(".status-select"))setStatus(event.target.dataset.statusId,event.target.value);if(event.target.matches(".select-radio"))selectOpportunity(event.target.closest("tr").dataset.id);});
els.detail.addEventListener("click",(event)=>{const star=event.target.closest("[data-bookmark-company]");if(star){toggleBookmark(star.dataset.bookmarkCompany);return;}const item=state.opportunities.find((x)=>x.id===state.selectedId);if(event.target.dataset.copy==="email"&&item?.contact_email)copyText(item.contact_email,"Email");if(event.target.dataset.copySubject&&item?.reply_subject)copyText(item.reply_subject,"Subject");if(event.target.dataset.copyResponse&&item?.reply_body)copyText(item.reply_body,"Response");if(event.target.dataset.markSent)markEmailSent();if(event.target.dataset.generateResponse)generateResponse();});
document.querySelectorAll("[data-view]").forEach((button)=>button.addEventListener("click",()=>{document.querySelectorAll("[data-view]").forEach((x)=>x.classList.remove("is-active"));button.classList.add("is-active");state.view=button.dataset.view;renderTable();}));
els.statusFilter.addEventListener("change",()=>{state.status=els.statusFilter.value;renderTable();}); els.fitFilter.addEventListener("change",()=>{state.minFit=Number(els.fitFilter.value);renderTable();}); els.connect.addEventListener("click",loadTeamState);els.find.addEventListener("click",runLiveSearch);

async function init(){els.accessCode.value=sessionStorage.getItem(ACCESS_SESSION_KEY)||"";try{const response=await fetch("/fixtures/opportunities.json");if(!response.ok)throw new Error(`Fixture load failed: ${response.status}`);state.opportunities=hydrateFixtureStatuses(await response.json());state.selectedId=state.opportunities[0]?.id||null;renderAll();if(accessCode())loadTeamState();}catch(error){els.body.innerHTML=`<tr><td colspan="13">${escapeHtml(error.message)}</td></tr>`;}}
init();
